export const fileTypesIcons = {
  folder: ['ti', 'ti-folder-filled'],
  txt: ["ti", "ti-file-filled"],
  js: ["ti", "ti-brand-javascript"],
  mjs: ["ti", "ti-brand-nodejs"],
  pdf: ["ti", "ti-file-type-pdf"],
  json: ["ti", "ti-code-dots"],
  html: ["ti", "ti-code"],
  py: ["ti", "ti-brand-python"],
  md: ["ti", "ti-markdown"],
  css: ["ti", "ti-brand-css3"],
  scss: ["ti", "ti-brand-sass"],
  jpeg: ["ti", "ti-photo"],
  png: ["ti", "ti-photo"],
  jpg: ["ti", "ti-photo"],
  zip: ["ti", "ti-file-zip"],
  exe: ["ti", "ti-cube"],
  docx: ["ti", "ti-file-type-docx"],
  apkg: ["ti", "ti-cards-filled"],
  mhtml: ["ti", "ti-brand-edge"],
  epub: ["ti", "ti-book-2"],
  webp: ["ti", "ti-brand-chrome"],
  mkv: ["ti", "ti-brand-vlc"],
  torrent: ["ti", "ti-file-download"],
  mp4: ["ti", "ti-movie"],
  mp3: ["ti", "ti-music"],
  sh: ["ti", "ti-brand-powershell"],
};